### ISSUE TITLE
How to use with vite 

### ISSUE THREAD

**Issue by Kokoserver** [arthurgermano/svelte-client-router#2]
I love svelte with vite, have tried using -single on the script is not working. 

Anyways thanks for your hard work on this

**Comment by arthurgermano** [comment]
Hi there.. 
i think that with vite there is an example here
https://github.com/arthurgermano/svelte-client-router/blob/main/docsproj/vite.config.js

Inside this folder docsproj.. also has a package.json with some npm commands you can use..

Or you can copy that folder too and adapt to your needs.

Should be pretty simple to make it work.
Just copy... 
Run npm install.. 
and then I think you can run npm run dev

Thanks.. and please let me now how the tests went and If it worked..

I am here to help.. I am off computer this weekend but as soon as the week start I will be more available..

Cheers 😃

**Comment by arthurgermano** [comment]
> I love svelte with vite, have tried using -single on the script is not working.
> 
> Anyways thanks for your hard work on this

The answer is in my previous comment 🙏🙏🙏🙏

**Comment by Kokoserver** [comment]
Thanks it works
